package commands

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/user/git-ai-trail/internal/git"
)

func InstallHooks(args []string) error {
	gitDir, err := git.GetGitDir()
	if err != nil {
		return err
	}
	
	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}
	
	postCommitPath := filepath.Join(hooksDir, "post-commit")
	
	hookContent := `#!/bin/sh
# git-ai-trail post-commit hook
# Auto-generated by 'git ai-trail install-hooks'

# Try to find git-ai-trail in PATH
if command -v git-ai-trail >/dev/null 2>&1; then
    git-ai-trail record
elif command -v git >/dev/null 2>&1 && git ai-trail record 2>/dev/null; then
    :
else
    echo "Warning: git-ai-trail not found in PATH. AI attribution not recorded." >&2
    echo "Install git-ai-trail and ensure it's in your PATH." >&2
fi
`
	
	if err := os.WriteFile(postCommitPath, []byte(hookContent), 0755); err != nil {
		return fmt.Errorf("failed to write post-commit hook: %w", err)
	}
	
	fmt.Println("Installed post-commit hook")
	fmt.Printf("  Location: %s\n", postCommitPath)
	fmt.Println()
	fmt.Println("The hook will automatically record AI attribution after each commit.")
	fmt.Println("Remember to run 'git ai-trail mark' before committing AI-generated changes.")
	
	return nil
}

func Init(args []string) error {
	if err := git.ConfigSet("notes.rewriteRef", "refs/notes/ai-trail"); err != nil {
		return fmt.Errorf("failed to set notes.rewriteRef: %w", err)
	}
	
	if err := git.ConfigSet("notes.rewrite.amend", "true"); err != nil {
		return fmt.Errorf("failed to set notes.rewrite.amend: %w", err)
	}
	
	if err := git.ConfigSet("notes.rewrite.rebase", "true"); err != nil {
		return fmt.Errorf("failed to set notes.rewrite.rebase: %w", err)
	}
	
	fetchSpec := "+refs/notes/ai-trail:refs/notes/ai-trail"
	_ = git.ConfigAdd("remote.origin.fetch", fetchSpec)
	
	fmt.Println("Initialized git-ai-trail for this repository")
	fmt.Println()
	fmt.Println("Configuration:")
	fmt.Println("  - Notes will survive amend and rebase")
	fmt.Println("  - Added fetch spec for ai-trail notes")
	fmt.Println()
	fmt.Println("To share AI attribution with your team:")
	fmt.Println("  git push origin refs/notes/ai-trail")
	fmt.Println()
	fmt.Println("To install the post-commit hook:")
	fmt.Println("  git ai-trail install-hooks")
	
	return nil
}
