package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Akasan/git-ai-trail/internal/git"
)

func InstallHooks(args []string) error {
	gitDir, err := git.GetGitDir()
	if err != nil {
		return err
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return fmt.Errorf("failed to create hooks directory: %w", err)
	}

	if err := installPostCommitHook(hooksDir); err != nil {
		return err
	}

	if err := installPrePushHook(hooksDir); err != nil {
		return err
	}

	return nil
}

func installPostCommitHook(hooksDir string) error {
	postCommitPath := filepath.Join(hooksDir, "post-commit")
	backupPath := postCommitPath + ".backup"

	existingContent, err := os.ReadFile(postCommitPath)
	isOurHook := err == nil && strings.Contains(string(existingContent), "git-ai-trail post-commit hook")

	if isOurHook {
		fmt.Println("git-ai-trail post-commit hook is already installed")
		return nil
	}

	if err == nil {
		if _, err := os.Stat(backupPath); err == nil {
			backupContent, err := os.ReadFile(backupPath)
			if err == nil && string(backupContent) != string(existingContent) {
				return fmt.Errorf("post-commit hook exists and differs from backup; refusing to overwrite.\nPlease manually merge or remove %s", postCommitPath)
			}
			fmt.Printf("Backup already exists at: %s\n", backupPath)
			fmt.Println("Skipping backup (current hook matches backup).")
		} else {
			if err := os.Rename(postCommitPath, backupPath); err != nil {
				return fmt.Errorf("failed to backup existing hook: %w", err)
			}
			fmt.Printf("Backed up existing hook to: %s\n", backupPath)
		}
	}

	hookContent := `#!/bin/sh
# git-ai-trail post-commit hook
# Auto-generated by 'git ai-trail install-hooks'

if command -v git-ai-trail >/dev/null 2>&1; then
    git-ai-trail record || exit_code=$?
elif command -v git >/dev/null 2>&1; then
    git ai-trail record || exit_code=$?
fi

if [ -x "$0.backup" ]; then
    "$0.backup" "$@"
fi
`

	if err := os.WriteFile(postCommitPath, []byte(hookContent), 0755); err != nil {
		return fmt.Errorf("failed to write post-commit hook: %w", err)
	}

	fmt.Println("Installed post-commit hook")
	fmt.Printf("  Location: %s\n", postCommitPath)
	fmt.Println()
	fmt.Println("The hook will automatically record AI attribution after each commit.")
	if _, err := os.Stat(backupPath); err == nil {
		fmt.Println("Your previous hook will be chained (called after git-ai-trail record).")
	}
	fmt.Println("Remember to run 'git ai-trail mark' before committing AI-generated changes.")
	fmt.Println()

	return nil
}

func installPrePushHook(hooksDir string) error {
	prePushPath := filepath.Join(hooksDir, "pre-push")
	backupPath := prePushPath + ".backup"

	existingContent, err := os.ReadFile(prePushPath)
	isOurHook := err == nil && strings.Contains(string(existingContent), "git-ai-trail pre-push hook")

	if isOurHook {
		fmt.Println("git-ai-trail pre-push hook is already installed")
		return nil
	}

	if err == nil {
		if _, err := os.Stat(backupPath); err == nil {
			backupContent, err := os.ReadFile(backupPath)
			if err == nil && string(backupContent) != string(existingContent) {
				return fmt.Errorf("pre-push hook exists and differs from backup; refusing to overwrite.\nPlease manually merge or remove %s", prePushPath)
			}
			fmt.Printf("Backup already exists at: %s\n", backupPath)
			fmt.Println("Skipping backup (current hook matches backup).")
		} else {
			if err := os.Rename(prePushPath, backupPath); err != nil {
				return fmt.Errorf("failed to backup existing hook: %w", err)
			}
			fmt.Printf("Backed up existing hook to: %s\n", backupPath)
		}
	}

	hookContent := `#!/bin/sh
# git-ai-trail pre-push hook
# Auto-generated by 'git ai-trail install-hooks'

remote="$1"
url="$2"

while read local_ref local_sha remote_ref remote_sha
do
    if [ "$local_sha" = "0000000000000000000000000000000000000000" ]; then
        continue
    fi
    
    if [ "$remote_sha" = "0000000000000000000000000000000000000000" ]; then
        range="$local_sha"
    else
        range="$remote_sha..$local_sha"
    fi
    
    if command -v git-ai-trail >/dev/null 2>&1; then
        if ! git-ai-trail verify --check "$range"; then
            echo "Push rejected: unverified AI-attributed changes detected"
            echo "Run 'git ai-trail verify' to verify your changes"
            exit 1
        fi
    elif command -v git >/dev/null 2>&1; then
        if ! git ai-trail verify --check "$range"; then
            echo "Push rejected: unverified AI-attributed changes detected"
            echo "Run 'git ai-trail verify' to verify your changes"
            exit 1
        fi
    fi
done

if [ -x "$0.backup" ]; then
    "$0.backup" "$@"
fi
`

	if err := os.WriteFile(prePushPath, []byte(hookContent), 0755); err != nil {
		return fmt.Errorf("failed to write pre-push hook: %w", err)
	}

	fmt.Println("Installed pre-push hook")
	fmt.Printf("  Location: %s\n", prePushPath)
	fmt.Println()
	fmt.Println("The hook will block pushes with unverified AI-attributed changes.")
	if _, err := os.Stat(backupPath); err == nil {
		fmt.Println("Your previous hook will be chained (called after git-ai-trail verify).")
	}
	fmt.Println()

	return nil
}

func Init(args []string) error {
	if err := git.ConfigSet("notes.rewriteRef", "refs/notes/ai-trail"); err != nil {
		return fmt.Errorf("failed to set notes.rewriteRef: %w", err)
	}

	if err := git.ConfigAdd("notes.rewriteRef", "refs/notes/ai-trail-verify"); err != nil {
		return fmt.Errorf("failed to add verify notes.rewriteRef: %w", err)
	}

	if err := git.ConfigSet("notes.rewrite.amend", "true"); err != nil {
		return fmt.Errorf("failed to set notes.rewrite.amend: %w", err)
	}

	if err := git.ConfigSet("notes.rewrite.rebase", "true"); err != nil {
		return fmt.Errorf("failed to set notes.rewrite.rebase: %w", err)
	}

	originURL, err := git.ConfigGet("remote.origin.url")
	if err == nil && originURL != "" {
		fetchSpec := "+refs/notes/ai-trail:refs/notes/ai-trail"
		verifyFetchSpec := "+refs/notes/ai-trail-verify:refs/notes/ai-trail-verify"

		existing, err := git.Run("config", "--get-all", "remote.origin.fetch")
		if err == nil {
			if !strings.Contains(existing, fetchSpec) {
				if err := git.ConfigAdd("remote.origin.fetch", fetchSpec); err != nil {
					fmt.Fprintf(os.Stderr, "Warning: failed to add fetch spec: %v\n", err)
				}
			}
			if !strings.Contains(existing, verifyFetchSpec) {
				if err := git.ConfigAdd("remote.origin.fetch", verifyFetchSpec); err != nil {
					fmt.Fprintf(os.Stderr, "Warning: failed to add verify fetch spec: %v\n", err)
				}
			}
		} else {
			if err := git.ConfigAdd("remote.origin.fetch", fetchSpec); err != nil {
				fmt.Fprintf(os.Stderr, "Warning: failed to add fetch spec: %v\n", err)
			}
			if err := git.ConfigAdd("remote.origin.fetch", verifyFetchSpec); err != nil {
				fmt.Fprintf(os.Stderr, "Warning: failed to add verify fetch spec: %v\n", err)
			}
		}
	}

	fmt.Println("Initialized git-ai-trail for this repository")
	fmt.Println()
	fmt.Println("Configuration:")
	fmt.Println("  - Notes will survive amend and rebase")
	if originURL != "" {
		fmt.Println("  - Added fetch spec for ai-trail notes")
		fmt.Println("  - Added fetch spec for ai-trail-verify notes")
	}
	fmt.Println()
	fmt.Println("To share AI attribution with your team:")
	fmt.Println("  git push origin refs/notes/ai-trail refs/notes/ai-trail-verify")
	fmt.Println()
	fmt.Println("To install hooks (post-commit and pre-push):")
	fmt.Println("  git ai-trail install-hooks")

	return nil
}
